sudo: required
services:
  - docker

scripts:
  - docker build -t msultzaberger/node .
  - docker images msultzaberger/node

before_deploy:
  - docker login -u msultzaberger -p Chief431!

deploy:
  provider: script
  script: docker push msultzaberger/node
  on:
    branch: master